# Generated by Django 6.0.1 on 2026-02-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producent",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Producent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producent",
                "verbose_name_plural": "Producenci",
            },
        ),
        migrations.CreateModel(
            name="Objaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nazwa objawu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Objaw",
                "verbose_name_plural": "Objawy",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Wiek")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Mężczyzna"), ("K", "Kobieta")],
                        max_length=1,
                        verbose_name="Płeć",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pacjent",
                "verbose_name_plural": "Pacjenci",
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lek", models.CharField(max_length=255, verbose_name="Lek")),
                (
                    "active_substance",
                    models.CharField(max_length=255, verbose_name="Substancja czynna"),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.manufacturer",
                        verbose_name="Producent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lek",
                "verbose_name_plural": "Leki",
            },
        ),
        migrations.CreateModel(
            name="Zdarzenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis zdarzenia")),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.drug",
                        verbose_name="Lek",
                    ),
                ),
                (
                    "objawy",
                    models.ManyToManyField(to="core.objaw", verbose_name="Objawy"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patient",
                        verbose_name="Pacjent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdarzenie",
                "verbose_name_plural": "Zdarzenia",
            },
        ),
    ]
