# Generated by Django 6.0.1 on 2026-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zdarzenie",
            name="nasilenie_po",
            field=models.IntegerField(
                default=5, verbose_name="Nasilenie objawów PO leku (1-10)"
            ),
        ),
        migrations.AddField(
            model_name="zdarzenie",
            name="nasilenie_przed",
            field=models.IntegerField(
                default=5, verbose_name="Nasilenie objawów PRZED lekiem (1-10)"
            ),
        ),
    ]
